name: dagger
on:
  push:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call Dagger Function to lint and test terraform
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          verb: call
          module: .dagger
          args: lint --directory="."