name: dagger
on:
  workflow_dispatch:
  # push:
  #   branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx Cache hack
        uses: docker/setup-buildx-action@v3
      
      - name: Call Dagger Function to lint and test terraform
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          verb: call
          module: .dagger
          args: lint --directory="."